//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisApp24.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DisApp24.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user account is no longer valid. Please log in again..
        /// </summary>
        internal static string AccountInvalidErrorMessage {
            get {
                return ResourceManager.GetString("AccountInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string AccountInvalidErrorTitle {
            get {
                return ResourceManager.GetString("AccountInvalidErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Date.
        /// </summary>
        internal static string CalendarPage_ConfirmButtonText {
            get {
                return ResourceManager.GetString("CalendarPage_ConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Date.
        /// </summary>
        internal static string CalendarPage_SelectedDateText {
            get {
                return ResourceManager.GetString("CalendarPage_SelectedDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment (optional).
        /// </summary>
        internal static string CommentPlaceholder {
            get {
                return ResourceManager.GetString("CommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your first name..
        /// </summary>
        internal static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your first name..
        /// </summary>
        internal static string EnterFirstNameError {
            get {
                return ResourceManager.GetString("EnterFirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your last name..
        /// </summary>
        internal static string EnterLastName {
            get {
                return ResourceManager.GetString("EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your last name..
        /// </summary>
        internal static string EnterLastNameError {
            get {
                return ResourceManager.GetString("EnterLastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password..
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string EnterValidEmail {
            get {
                return ResourceManager.GetString("EnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string EnterValidEmailError {
            get {
                return ResourceManager.GetString("EnterValidEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number..
        /// </summary>
        internal static string EnterValidPhoneError {
            get {
                return ResourceManager.GetString("EnterValidPhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number..
        /// </summary>
        internal static string EnterValidPhoneNumber {
            get {
                return ResourceManager.GetString("EnterValidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string LoginPage_EmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue as Guest.
        /// </summary>
        internal static string LoginPage_GuestContinue {
            get {
                return ResourceManager.GetString("LoginPage_GuestContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPage_LoginButtonText {
            get {
                return ResourceManager.GetString("LoginPage_LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Google.
        /// </summary>
        internal static string LoginPage_LoginWithGoogle {
            get {
                return ResourceManager.GetString("LoginPage_LoginWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account?.
        /// </summary>
        internal static string LoginPage_NoAccount {
            get {
                return ResourceManager.GetString("LoginPage_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPage_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in.
        /// </summary>
        internal static string LoginPage_PleaseSignIn {
            get {
                return ResourceManager.GetString("LoginPage_PleaseSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Register here.
        /// </summary>
        internal static string LoginPage_RegisterHere {
            get {
                return ResourceManager.GetString("LoginPage_RegisterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Appointments.
        /// </summary>
        internal static string MyAppointmentsHeader {
            get {
                return ResourceManager.GetString("MyAppointmentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No date selected.
        /// </summary>
        internal static string NoDateSelected {
            get {
                return ResourceManager.GetString("NoDateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered passwords do not match..
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number (optional).
        /// </summary>
        internal static string PhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("PhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already registered?.
        /// </summary>
        internal static string RegistrationPage_AlreadyRegisteredText {
            get {
                return ResourceManager.GetString("RegistrationPage_AlreadyRegisteredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string RegistrationPage_ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPage_ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string RegistrationPage_EmailPlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPage_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string RegistrationPage_FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPage_FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Login.
        /// </summary>
        internal static string RegistrationPage_GoToLoginText {
            get {
                return ResourceManager.GetString("RegistrationPage_GoToLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string RegistrationPage_LastNamePlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPage_LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegistrationPage_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPage_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number (optional).
        /// </summary>
        internal static string RegistrationPage_PhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPage_PhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegistrationPage_RegisterButtonText {
            get {
                return ResourceManager.GetString("RegistrationPage_RegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegistrationPage_Title {
            get {
                return ResourceManager.GetString("RegistrationPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully created, and you have been automatically signed in..
        /// </summary>
        internal static string RegistrationSuccessMessage {
            get {
                return ResourceManager.GetString("RegistrationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending your reservation request. Please try again later..
        /// </summary>
        internal static string ReservationFailedMessage {
            get {
                return ResourceManager.GetString("ReservationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ReservationFailedTitle {
            get {
                return ResourceManager.GetString("ReservationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Management.
        /// </summary>
        internal static string ReservationManagementTitle {
            get {
                return ResourceManager.GetString("ReservationManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reservation request has been successfully sent. You will receive a confirmation by email once your reservation has been confirmed..
        /// </summary>
        internal static string ReservationSuccessMessage {
            get {
                return ResourceManager.GetString("ReservationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ReservationSuccessTitle {
            get {
                return ResourceManager.GetString("ReservationSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        internal static string ReserveButtonText {
            get {
                return ResourceManager.GetString("ReserveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        internal static string ReserveTabText {
            get {
                return ResourceManager.GetString("ReserveTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Resource.
        /// </summary>
        internal static string ResourcePickerTitle {
            get {
                return ResourceManager.GetString("ResourcePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a date before confirming..
        /// </summary>
        internal static string SelectDateBeforeConfirming {
            get {
                return ResourceManager.GetString("SelectDateBeforeConfirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a date..
        /// </summary>
        internal static string SelectDateError {
            get {
                return ResourceManager.GetString("SelectDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Date.
        /// </summary>
        internal static string SelectDateLabel {
            get {
                return ResourceManager.GetString("SelectDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a resource..
        /// </summary>
        internal static string SelectResourceError {
            get {
                return ResourceManager.GetString("SelectResourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a time..
        /// </summary>
        internal static string SelectTimeError {
            get {
                return ResourceManager.GetString("SelectTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Time.
        /// </summary>
        internal static string SelectTimeTitle {
            get {
                return ResourceManager.GetString("SelectTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignInButtonText_SignedIn {
            get {
                return ResourceManager.GetString("SignInButtonText_SignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInButtonText_SignedOut {
            get {
                return ResourceManager.GetString("SignInButtonText_SignedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
    }
}
